//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.03.03 at 08:22:14 AM EET 
//


package package_1.essence.telephone;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

import package_1.essence.Product;


/**
 * <p>Java class for Telephone complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Telephone">
 *   &lt;complexContent>
 *     &lt;extension base="{http://order.nure.ua/essence/}Essence">
 *       &lt;sequence>
 *         &lt;element name="title" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="manufacture" type="{http://order.nure.ua/essence/telephone/}Manufacture" maxOccurs="unbounded"/>
 *         &lt;element name="batch_number" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;pattern value="BATCH_NUMBER-[0-9]{5,5}-[0-9]{4,4}"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="price" type="{http://order.nure.ua/essence/telephone/}Price"/>
 *         &lt;element name="category" type="{http://order.nure.ua/essence/telephone/}Category"/>
 *         &lt;element name="count">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}int">
 *               &lt;minInclusive value="0"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Telephone", propOrder = {
    "title",
    "manufacture",
    "batch_number",
    "price",
    "category",
    "count",
    "description",
    "cover",
})
public class Telephone extends Product {

	@XmlElement(required = true)
    protected String title;
    @XmlElement(required = true)
    protected List<Manufacture> manufacture;
    protected String batch_number;
    @XmlElement(required = true, defaultValue = "none")
    protected Category category;
    @XmlElement(defaultValue = "0")
    protected int count;
    protected String description;
    protected String cover;

    public Telephone() {
		super();
	}

	public Telephone(String title, List<Manufacture> manufacture, String batch_number, double price, Category category, int count) {
		super();
		this.title = title;
		this.manufacture = manufacture;
		this.batch_number = batch_number;
		this.price = price;
		this.category = category;
		this.count = count;
	}

	public Telephone(Integer id, String title, List<Manufacture> manufacture, String batch_number, double price, Category category,
			int count) {
		super(id);
		this.title = title;
		this.manufacture = manufacture;
		this.batch_number = batch_number;
		this.price = price;
		this.category = category;
		this.count = count;
	}

	/**
     * Gets the value of the title property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTitle() {
        return title;
    }

    /**
     * Sets the value of the title property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTitle(String value) {
        this.title = value;
    }

    /**
     * Gets the value of the manufacture property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the manufacture property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManufacture().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Manufacture }
     * 
     * 
     */
    public List<Manufacture> getManufacture() {
        if (manufacture == null) {
            manufacture = new ArrayList<Manufacture>();
        }
        return this.manufacture;
    }

    public String manufactures() {
    	if (manufacture == null) {
    		manufacture = new ArrayList<Manufacture>();
    		return "";
    	}
    	StringBuilder res = new StringBuilder();
    	for (Manufacture a : manufacture) {
			res.append(a.getTitle());
			res.append(",");
		}
    	res.setLength(res.length() - 1);
    	return res.toString();
    }
    
    public void setManufacture(String manufacture) {
		String[] manufactures = manufacture.split("\\s*,\\s*");
		ArrayList<Manufacture> items = new ArrayList<>();
		for (String a : manufactures) {
			items.add(new Manufacture(a));
		}
		this.manufacture = items;
	}

	/**
     * Gets the value of the batch_number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBatch_number() {
        return batch_number;
    }

    /**
     * Sets the value of the batch_number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBatch_number(String value) {
        this.batch_number = value;
    }

    /**
     * Gets the value of the price property.
     * 
     */
    public double getPrice() {
        return price;
    }

    /**
     * Sets the value of the price property.
     * 
     */
    public void setPrice(double value) {
        this.price = value;
    }

    /**
     * Gets the value of the category property.
     * 
     * @return
     *     possible object is
     *     {@link Category }
     *     
     */
    public Category getCategory() {
        return category;
    }

    /**
     * Sets the value of the category property.
     * 
     * @param value
     *     allowed object is
     *     {@link Category }
     *     
     */
    public void setCategory(Category value) {
        this.category = value;
    }

    /**
     * Gets the value of the count property.
     * 
     */
    public int getCount() {
        return count;
    }

    /**
     * Sets the value of the count property.
     * 
     */
    public void setCount(int value) {
        this.count = value;
    }

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCover() {
		return cover;
	}

	public void setCover(String cover) {
		this.cover = cover;
	}

	@Override
	public String toString() {
		StringBuilder builder = new StringBuilder();
		builder.append("Telephone [id=");
		builder.append(id);
		builder.append(", price=");
		builder.append(price);
		builder.append(", title=");
		builder.append(title);
		builder.append(", manufacture=");
		builder.append(manufacture);
		builder.append(", batch_number=");
		builder.append(batch_number);
		builder.append(", category=");
		builder.append(category);
		builder.append(", count=");
		builder.append(count);
		builder.append("]\n");
		return builder.toString();
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = super.hashCode();
		result = prime * result + ((title == null) ? 0 : title.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (!super.equals(obj))
			return false;
		if (!(obj instanceof Telephone))
			return false;
		Telephone other = (Telephone) obj;
		if (title == null) {
			if (other.title != null)
				return false;
		} else if (!title.equals(other.title))
			return false;
		return true;
	}

}
